FROM golang:1.8.3-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache git openssh

RUN go get -u github.com/adjust/rmq
RUN go get -u github.com/golang/glog

ADD . /go/src/github.com/n1207n/video-transcode-queue/task_queue

RUN go install github.com/n1207n/video-transcode-queue/task_queue/consumer

WORKDIR /go/src/github.com/n1207n/video-transcode-queue/task_queue

ENTRYPOINT /go/bin/consumer

EXPOSE 6379
